const Data = [
  {
    name: "Apple",
    price: 3,
    type: "fruit",
    actual_price: 0,
  },
  {
    name: "Orange",
    price: 4,
    type: "fruit",
    actual_price: 0,
  },
  {
    name: "Coke",
    price: 1,
    type: "Soft Drink",
    actual_price: 0,
  },
  {
    name: "Sprite",
    price: 1,
    type: "Soft Drink",
    actual_price: 0,
  },
  {
    name: "7Up",
    price: 1,
    type: "Soft Drink",
    actual_price: 0,
  },
  {
    name: "Fanta",
    price: 1,
    type: "Soft Drink",
    actual_price: 0,
  },
  {
    name: "Mango",
    price: 1,
    type: "Juice",
    actual_price: 0,
  },
  {
    name: "Orange",
    price: 1,
    type: "Juice",
    actual_price: 0,
  },
  {
    name: "Falsa",
    price: 1,
    type: "Juice",
    actual_price: 0,
  },
  {
    name: "Pine Apple",
    price: 1,
    type: "Apple",
    actual_price: 0,
  },
  {
    name: "Straberry",
    price: 1,
    type: "Juice",
    actual_price: 0,
  },
  {
    name: "Apple",
    price: 1,
    type: "Juice",
    actual_price: 0,
  },
  {
    name: "Rio",
    price: 1,
    type: "Biscuits",
    actual_price: 0,
  },
  {
    name: "Oreo",
    price: 1,
    type: "Biscuits",
    actual_price: 0,
  },
  {
    name: "Tuc",
    price: 1,
    type: "Biscuits",
    actual_price: 0,
  },
  {
    name: "Nan Khattai",
    price: 1,
    type: "Biscuits",
    actual_price: 0,
  },
  {
    name: "Zera Plus",
    price: 1,
    type: "Biscuits",
    actual_price: 0,
  },
  {
    name: "Candy",
    price: 1,
    type: "Biscuits",
    actual_price: 0,
  },
  {
    name: "Burger",
    price: 5,
    type: "Fast Food",
    actual_price: 0,
  },
  {
    name: "Pizza",
    price: 5,
    type: "Fast Food",
    actual_price: 0,
  },
  {
    name: "Shuwarma",
    price: 5,
    type: "Fast Food",
    actual_price: 0,
  },
  {
    name: "SandWitche",
    price: 5,
    type: "Fast Food",
    actual_price: 0,
  },
  {
    name: "Zinger Burger",
    price: 5,
    type: "Fast Food",
    actual_price: 0,
  },
];
export default Data;
